package gottsch.mdinator.output;

import gottsch.mdinator.model.ProcessingConfig;
import gottsch.mdinator.model.SourceFile;
import gottsch.mdinator.util.TokenEstimator;

import java.io.BufferedWriter;
import java.io.IOException;
import java.io.Writer;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Renders a list of source files into a single Markdown document.
 *
 * <p>Can be used in two modes:
 * <ul>
 *   <li><b>Single-file mode</b>: constructed with just the config.</li>
 *   <li><b>Split mode</b>: constructed with config + a {@code dirContext}
 *       string that is shown in the header to identify which directory
 *       this chunk represents.</li>
 * </ul>
 */
public final class MarkdownWriter {

    private static final DateTimeFormatter TS_FMT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss z");

    private final ProcessingConfig config;
    private final String dirContext;

    public MarkdownWriter(ProcessingConfig config) {
        this(config, null);
    }

    public MarkdownWriter(ProcessingConfig config, String dirContext) {
        this.config     = config;
        this.dirContext = dirContext;
    }

    public void write(Writer writer, List<SourceFile> files, String tree) throws IOException {
        // Build anchor assignments once — shared by TOC and file sections
        Map<String, String> anchorMap = buildAnchorMap(files);

        try (BufferedWriter bw = new BufferedWriter(writer)) {
            writeHeader(bw, files);
            if (config.isIncludeToc())  writeToc(bw, files, anchorMap);
            if (config.isIncludeTree()) writeTree(bw, tree);
            writeFiles(bw, files, anchorMap);
            writeFooter(bw, files);
        }
    }

    /**
     * Assigns a unique anchor to every file up front. Both writeToc() and
     * writeFiles() look up from this map so they always agree.
     */
    private static Map<String, String> buildAnchorMap(List<SourceFile> files) {
        Map<String, String> anchorMap    = new LinkedHashMap<>();
        Map<String, Integer> seenCounts  = new HashMap<>();

        for (SourceFile f : files) {
            String base  = toAnchor(f.getRelativePathString());
            int    count = seenCounts.merge(base, 1, Integer::sum);
            anchorMap.put(f.getRelativePathString(), count == 1 ? base : base + "-" + count);
        }
        return anchorMap;
    }

    // ── Header ───────────────────────────────────────────────────────────────

    private void writeHeader(BufferedWriter w, List<SourceFile> files) throws IOException {
        String repoName = config.getRepoPath().getFileName() != null
                ? config.getRepoPath().getFileName().toString()
                : config.getRepoPath().toString();

        if (dirContext != null && !dirContext.isEmpty()) {
            w.write("# Repository Context: `" + repoName + "` — `" + dirContext + "`\n\n");
        } else {
            w.write("# Repository Context: `" + repoName + "`\n\n");
        }

        w.write("> **Generated by md-inator** · " + ZonedDateTime.now().format(TS_FMT) + "\n");
        w.write(">\n");
        w.write("> | Property | Value |\n");
        w.write("> |---|---|\n");
        w.write("> | Repo path | `" + config.getRepoPath() + "` |\n");
        if (dirContext != null) {
            w.write("> | Directory | `" + dirContext + "` |\n");
        }
        w.write("> | Include patterns | `" + String.join("`, `", config.getIncludePatterns()) + "` |\n");
        if (!config.getExcludePatterns().isEmpty()) {
            w.write("> | Exclude patterns | `" + String.join("`, `", config.getExcludePatterns()) + "` |\n");
        }
        w.write("> | Files included | " + files.size() + " |\n");
        w.write("> | Comment stripping | " + (config.isStripComments() ? "enabled" : "disabled") + " |\n");
        w.write("\n---\n\n");
    }

    // ── TOC ──────────────────────────────────────────────────────────────────

    private void writeToc(BufferedWriter w, List<SourceFile> files,
                          Map<String, String> anchorMap) throws IOException {
        w.write("## Table of Contents\n\n");
        for (SourceFile f : files) {
            String anchor = anchorMap.get(f.getRelativePathString());
            w.write("- [`" + f.getRelativePathString() + "`](#" + anchor + ")\n");
        }
        w.write("\n---\n\n");
    }

    // ── Tree ─────────────────────────────────────────────────────────────────

    private void writeTree(BufferedWriter w, String tree) throws IOException {
        w.write("## Repository Structure\n\n");
        w.write(tree);
        w.write("\n---\n\n");
    }

    // ── Files ─────────────────────────────────────────────────────────────────

    private void writeFiles(BufferedWriter w, List<SourceFile> files,
                            Map<String, String> anchorMap) throws IOException {
        w.write("## Source Files\n\n");
        for (SourceFile f : files) {
            writeFile(w, f, anchorMap.get(f.getRelativePathString()));
        }
    }

    private void writeFile(BufferedWriter w, SourceFile f, String anchor) throws IOException {
        w.write("### <a id=\"" + anchor + "\"></a>`" + f.getRelativePathString() + "`\n\n");
        w.write(String.format(
                "> **Language:** %s · **Size:** %.1f KB%n%n",
                f.getLanguage().isEmpty() ? "text" : f.getLanguage(),
                f.getSizeBytes() / 1024.0
        ));
        w.write("```" + f.getLanguage() + "\n");
        w.write(ensureTrailingNewline(f.getContent()));
        w.write("```\n\n");
        w.write("---\n\n");
    }

    // ── Footer ────────────────────────────────────────────────────────────────

    private void writeFooter(BufferedWriter w, List<SourceFile> files) throws IOException {
        long totalBytes = files.stream().mapToLong(SourceFile::getSizeBytes).sum();
        w.write("<!-- md-inator: " + files.size() + " files, "
                + String.format("%.1f", totalBytes / 1024.0) + " KB total -->\n");
    }

    // ── Anchor helpers ────────────────────────────────────────────────────────

    /**
     * Converts a relative file path to a lowercase hyphen-separated anchor slug.
     * e.g. "src/main/App.java" → "src-main-app-java"
     */
    public static String toAnchor(String relPath) {
        return relPath.toLowerCase()
                .replaceAll("[^a-z0-9]+", "-")
                .replaceAll("^-|-$", "");
    }

    /**
     * Estimates the token cost of rendering a single SourceFile as it would
     * appear in the final Markdown output (heading, meta line, code fence,
     * separator). Used by ChunkProcessor to make accurate chunk boundaries
     * without a full render pass.
     */
    public static long estimateRenderedTokens(SourceFile f) {
        long chars = 0;
        chars += 10 + f.getRelativePathString().length() * 2; // anchor + heading
        chars += 40;                                           // meta line
        chars += 8;                                            // fence open
        chars += f.getContent().length();                      // content
        chars += 5;                                            // fence close
        chars += 5;                                            // separator
        return TokenEstimator.estimateFromBytes(chars);
    }

    private static String ensureTrailingNewline(String s) {
        return s.endsWith("\n") ? s : s + "\n";
    }
}
