package gottsch.mdinator.output;

import gottsch.mdinator.model.ProcessingConfig;
import gottsch.mdinator.model.SourceFile;

import java.io.BufferedWriter;
import java.io.IOException;
import java.io.Writer;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Renders a list of source files into a single Markdown document.
 *
 * <p>Can be used in two modes:
 * <ul>
 *   <li><b>Single-file mode</b>: constructed with just the config.</li>
 *   <li><b>Split mode</b>: constructed with config + a {@code dirContext}
 *       string that is shown in the header to identify which directory
 *       this chunk represents.</li>
 * </ul>
 */
public final class MarkdownWriter {

    private static final DateTimeFormatter TS_FMT =
        DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss z");

    private final ProcessingConfig config;
    private final String dirContext;   // null in single-file mode

    /** Single-file mode constructor. */
    public MarkdownWriter(ProcessingConfig config) {
        this(config, null);
    }

    /** Split mode constructor. */
    public MarkdownWriter(ProcessingConfig config, String dirContext) {
        this.config     = config;
        this.dirContext = dirContext;
    }

    public void write(Writer writer, List<SourceFile> files, String tree) throws IOException {
        try (BufferedWriter bw = new BufferedWriter(writer)) {
            writeHeader(bw, files);
            if (config.isIncludeToc())  writeToc(bw, files);
            if (config.isIncludeTree()) writeTree(bw, tree);
            writeFiles(bw, files);
            writeFooter(bw, files);
        }
    }

    // -------------------------------------------------------------------------

    private void writeHeader(BufferedWriter w, List<SourceFile> files) throws IOException {
        String repoName = config.getRepoPath().getFileName() != null
            ? config.getRepoPath().getFileName().toString()
            : config.getRepoPath().toString();

        // Title differs between single-file and split mode
        if (dirContext != null && !dirContext.isEmpty()) {
            w.write("# Repository Context: `" + repoName + "` — `" + dirContext + "`\n\n");
        } else {
            w.write("# Repository Context: `" + repoName + "`\n\n");
        }

        w.write("> **Generated by md-inator** · " + ZonedDateTime.now().format(TS_FMT) + "\n");
        w.write(">\n");
        w.write("> | Property | Value |\n");
        w.write("> |---|---|\n");
        w.write("> | Repo path | `" + config.getRepoPath() + "` |\n");
        if (dirContext != null) {
            w.write("> | Directory | `" + dirContext + "` |\n");
        }
        w.write("> | Include patterns | `" + String.join("`, `", config.getIncludePatterns()) + "` |\n");
        if (!config.getExcludePatterns().isEmpty()) {
            w.write("> | Exclude patterns | `" + String.join("`, `", config.getExcludePatterns()) + "` |\n");
        }
        w.write("> | Files included | " + files.size() + " |\n");
        w.write("> | Comment stripping | " + (config.isStripComments() ? "enabled" : "disabled") + " |\n");
        w.write("\n---\n\n");
    }

    private void writeToc(BufferedWriter w, List<SourceFile> files) throws IOException {
        w.write("## Table of Contents\n\n");
        for (SourceFile f : files) {
            String anchor = toAnchor(f.getRelativePathString());
            w.write("- [`" + f.getRelativePathString() + "`](#" + anchor + ")\n");
        }
        w.write("\n---\n\n");
    }

    private void writeTree(BufferedWriter w, String tree) throws IOException {
        w.write("## Repository Structure\n\n");
        w.write(tree);
        w.write("\n---\n\n");
    }

    private void writeFiles(BufferedWriter w, List<SourceFile> files) throws IOException {
        w.write("## Source Files\n\n");
        for (SourceFile f : files) {
            writeFile(w, f);
        }
    }

    private void writeFile(BufferedWriter w, SourceFile f) throws IOException {
        String anchor = toAnchor(f.getRelativePathString());
        w.write("### <a id=\"" + anchor + "\"></a>`" + f.getRelativePathString() + "`\n\n");
        w.write(String.format(
            "> **Language:** %s · **Size:** %.1f KB%n%n",
            f.getLanguage().isEmpty() ? "text" : f.getLanguage(),
            f.getSizeBytes() / 1024.0
        ));
        String lang = f.getLanguage();
        w.write("```" + lang + "\n");
        w.write(ensureTrailingNewline(f.getContent()));
        w.write("```\n\n");
        w.write("---\n\n");
    }

    private void writeFooter(BufferedWriter w, List<SourceFile> files) throws IOException {
        long totalBytes = files.stream().mapToLong(SourceFile::getSizeBytes).sum();
        w.write("<!-- md-inator: " + files.size() + " files, "
            + String.format("%.1f", totalBytes / 1024.0) + " KB total -->\n");
    }

    // -------------------------------------------------------------------------

    /**
     * Converts a relative path string to a GitHub-compatible anchor id.
     * e.g. {@code src/main/App.java} → {@code src-main-app-java}
     */
    public static String toAnchor(String relPath) {
        return relPath.toLowerCase()
            .replaceAll("[^a-z0-9]+", "-")
            .replaceAll("^-|-$", "");
    }

    private static String ensureTrailingNewline(String s) {
        return s.endsWith("\n") ? s : s + "\n";
    }
}
